apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-flask-app
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challenge-flask-app
  template:
    metadata:
      labels:
        app: challenge-flask-app
    spec:
      containers:
        - name: challenge-flask-app
          image: flask-challenge-app
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
          readinessProbe:
            initialDelaySeconds: 10
              exec:
                command:
                  - /bin/sh
                  - -c
                  - echo hola mundo
          livenessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - /bin/sh
                - -c
                -  echo hola mundo