apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: challenge-flask-app
  namespace: devops
spec:
  rules:
    - host: python-app.demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: challenge-flask-app
              servicePort: http