apiVersion: v1
kind: Service
metadata:
  name: challenge-flask-app
  namespace: devops
spec:
  type: NodePort
  selector:
    app-name: flask-app
  ports:
    - name : app-port
      nodePort: 30163
      port: 8000
      targetPort: 8000
